# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-11 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_html',
            field=models.TextField(default=23, editable=False),
            preserve_default=False,
        ),
    ]
